import { describe, expect, it } from 'vitest';
import { normalizeLiveText, parseLiveComment } from './live-parser.js';

// Synthetic Vietnamese shop catalog. Expected results below are explicit business
// examples, not generated by the parser. A suggestion is never a sale/stock write.
const catalog = {
  products: [
    ['g01', 'JEAN-XANH-M', 'Quần jeans xanh M'],
    ['g02', 'JEAN-ĐỎ-L', 'Quần jeans đỏ L'],
    ['g03', 'JEAN-XANH-L', 'Quần jeans xanh L'],
    ['g04', '1024', 'Quần jeans xanh đậm 29'],
    ['g05', 'CV12-TRẮNG-S', 'Chân váy trắng S'],
    ['g06', 'CV12-BE-S', 'Chân váy be S'],
    ['g07', 'AO7-ĐỎ-ĐÔ-XL', 'Áo đỏ đô XL'],
    ['g08', 'AO7-KEM-M', 'Áo kem M'],
    ['g09', 'AO-HỒNG-FREESIZE', 'Áo hồng phấn freesize'],
    ['g10', 'QT9-ĐEN-29', 'Quần tây đen 29'],
    ['g11', 'QT9-ĐEN-30', 'Quần tây đen 30'],
    ['g12', 'SET.XANH/M', 'Set xanh ngọc M'],
    ['g13', 'TẠM', 'Hàng tạm chưa đối chiếu'],
    ['g14', 'CŨ', 'SKU cũ chưa gán biến thể'],
  ].map(([id, code, name]) => ({ id, code, name, provisional: id === 'g13' })),
  styles: [
    ['s49', '49'],
    ['s29', 'JEAN29'],
    ['scv', 'CV12'],
    ['sao', 'ÁO7'],
    ['shong', 'HỒNG'],
    ['sqt', 'QT9'],
    ['sset', 'SET'],
  ].map(([id, code]) => ({ id, code })),
  variants: [
    ['g01', 's49', 'M', 'Xanh'],
    ['g02', 's49', 'L', 'Đỏ'],
    ['g03', 's49', 'L', 'Xanh'],
    ['g04', 's29', '29', 'Xanh đậm'],
    ['g05', 'scv', 'S', 'Trắng'],
    ['g06', 'scv', 'S', 'Be'],
    ['g07', 'sao', 'XL', 'Đỏ đô'],
    ['g08', 'sao', 'M', 'Kem'],
    ['g09', 'shong', 'Freesize', 'Hồng phấn'],
    ['g10', 'sqt', '29', 'Đen'],
    ['g11', 'sqt', '30', 'Đen'],
    ['g12', 'sset', 'M', 'Xanh ngọc'],
    ['g13', null, 'M', 'Đỏ'],
  ].map(([id, style_id, size, color]) => ({
    id,
    product_id: id,
    style_id,
    size,
    color,
    mapping_status: id === 'g13' ? 'needs_review' : 'confirmed',
  })),
  aliases: [
    ['Q49', 'g01'],
    ['Q49', 'g02'],
    ['Q49', 'g03'],
    ['quần xanh', 'g01'],
    ['quần xanh', 'g03'],
    ['quần xanh đậm', 'g04'],
    ['váy trắng', 'g05'],
    ['váy be', 'g06'],
    ['áo đỏ đô', 'g07'],
    ['áo kem', 'g08'],
    ['áo hồng', 'g09'],
    ['quần tây', 'g10'],
    ['quần tây', 'g11'],
    ['set xanh', 'g12'],
    ['mẫu thử', 'g13'],
    ['combo 2c', 'g12'],
    ['1000', 'g08'],
    ['SKU_01', 'g01'],
    ['🌸 hồng', 'g09'],
  ]
    .map(([alias_text, product_id]) => ({ alias_text, product_id, active: true }))
    .concat({ alias_text: 'hết', product_id: 'g02', active: false }),
};

function freeze(value) {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
}
freeze(catalog);
const unique = (label, text, product_id, quantity = 1, quantity_source = 'default') => ({
  label,
  text,
  expected: { status: 'unique', product_id, quantity, quantity_source },
  ids: [product_id],
});
const ambiguous = (label, text, ids, quantity = 1, quantity_source = 'default') => ({
  label,
  text,
  expected: {
    status: 'ambiguous',
    product_id: null,
    quantity,
    quantity_source,
    reason: 'MULTIPLE_SKUS',
  },
  ids,
});
const rejected = (label, text, reason) => ({
  label,
  text,
  expected: { status: 'no_match', product_id: null, ...(reason ? { reason } : {}) },
});
const review = (label, text, product_id, override) => ({
  label,
  text,
  override,
  expected: { status: 'needs_review', product_id: null, reason: 'UNREVIEWED_VARIANT' },
  ids: [product_id],
});

const exactCases = [
  unique('mã SKU quần xanh M', 'JEAN-XANH-M', 'g01'),
  unique('mã SKU quần đỏ L', 'JEAN-ĐỎ-L', 'g02'),
  unique('mã SKU quần xanh L', 'JEAN-XANH-L', 'g03'),
  unique('mã hàng hoàn toàn bằng số', '1024', 'g04'),
  unique('mã váy trắng có dấu', 'CV12-TRẮNG-S', 'g05'),
  unique('mã váy be', 'CV12-BE-S', 'g06'),
  unique('mã áo màu đỏ đô', 'AO7-ĐỎ-ĐÔ-XL', 'g07'),
  unique('mã áo kem', 'AO7-KEM-M', 'g08'),
  unique('mã áo freesize', 'AO-HỒNG-FREESIZE', 'g09'),
  unique('mã quần tây cỡ 29', 'QT9-ĐEN-29', 'g10'),
  unique('mã quần tây cỡ 30', 'QT9-ĐEN-30', 'g11'),
  unique('mã hàng giữ nguyên chấm và gạch chéo', 'SET.XANH/M', 'g12'),
  unique('bí danh váy trắng', 'váy trắng', 'g05'),
  unique('bí danh váy be', 'váy be', 'g06'),
  unique('bí danh áo đỏ đô', 'áo đỏ đô', 'g07'),
  unique('bí danh áo kem', 'áo kem', 'g08'),
  unique('bí danh áo hồng', 'áo hồng', 'g09'),
  unique('bí danh set xanh', 'set xanh', 'g12'),
  unique('bí danh số không trở thành số lượng', '1000', 'g08'),
  unique('bí danh chứa hậu tố 2c không bị tách', 'combo 2c', 'g12'),
  unique('bí danh gạch dưới đã đăng ký', 'SKU_01', 'g01'),
  unique('emoji chỉ hợp lệ khi đã đăng ký trong bí danh', '🌸 hồng', 'g09'),
];

const attributeCases = [
  unique('mã mẫu màu rồi cỡ', '49 xanh m', 'g01'),
  unique('mã mẫu cỡ rồi màu', '49 m xanh', 'g01'),
  unique('phân biệt xanh L và xanh M', '49 xanh l', 'g03'),
  unique('đảo thuộc tính xanh L', '49 l xanh', 'g03'),
  unique('mẫu đỏ L', '49 đỏ l', 'g02'),
  unique('đảo thuộc tính đỏ L', '49 l đỏ', 'g02'),
  unique('chỉ cỡ M đủ duy nhất trong mẫu', '49 m', 'g01'),
  unique('chỉ màu đỏ đủ duy nhất trong mẫu', '49 đỏ', 'g02'),
  unique('bí danh chung chọn cỡ M', 'quần xanh m', 'g01'),
  unique('bí danh chung chọn cỡ L', 'quần xanh l', 'g03'),
  unique('bí danh chung chọn đủ thuộc tính', 'q49 đỏ l', 'g02'),
  unique('màu nhiều từ đứng trước cỡ số', 'jean29 xanh đậm 29', 'g04'),
  unique('cỡ số đứng trước màu nhiều từ', 'jean29 29 xanh đậm', 'g04'),
  unique('cỡ số của SKU không bị coi là số lượng', '1024 29', 'g04'),
  unique('quần tây chọn cỡ số 30', 'qt9 30', 'g11'),
  unique('quần tây chọn đen 29', 'quần tây đen 29', 'g10'),
  unique('quần tây chọn cỡ rồi màu', 'quần tây 30 đen', 'g11'),
  unique('mẫu váy chọn màu trắng', 'cv12 trắng', 'g05'),
  unique('mẫu váy chọn màu be và cỡ', 'cv12 be s', 'g06'),
  unique('mẫu váy đảo cỡ và màu', 'cv12 s trắng', 'g05'),
  unique('mẫu áo chọn đỏ đô XL', 'áo7 đỏ đô xl', 'g07'),
  unique('mẫu áo đảo XL và đỏ đô', 'áo7 xl đỏ đô', 'g07'),
  unique('mẫu áo chọn kem M', 'áo7 kem m', 'g08'),
  unique('mẫu áo chỉ cỡ XL đã duy nhất', 'áo7 xl', 'g07'),
  unique('freesize với màu hồng phấn', 'hồng hồng phấn freesize', 'g09'),
  unique('freesize đứng trước màu', 'hồng freesize hồng phấn', 'g09'),
  unique('set cỡ M rồi màu xanh ngọc', 'set m xanh ngọc', 'g12'),
  unique('bí danh dài hơn được ưu tiên', 'quần xanh đậm 29', 'g04'),
];

const quantityCases = [
  unique('hai quần ký hiệu c liền', '49 xanh m 2c', 'g01', 2, 'explicit_marker'),
  unique('ba quần ký hiệu c cách', '49 xanh l 3 c', 'g03', 3, 'explicit_marker'),
  unique('một quần ký hiệu cái', '49 đỏ l 1 cái', 'g02', 1, 'explicit_marker'),
  unique('hai váy ký hiệu chiếc', 'váy trắng 2 chiếc', 'g05', 2, 'explicit_marker'),
  unique('bốn váy ký hiệu cái liền', 'váy be 4cái', 'g06', 4, 'explicit_marker'),
  unique('hai áo ký hiệu chiếc liền', 'áo kem 2chiếc', 'g08', 2, 'explicit_marker'),
  unique('năm áo ký hiệu x', 'áo đỏ đô x5', 'g07', 5, 'explicit_marker'),
  unique('ba áo ký hiệu x cách số', 'áo hồng x 3', 'g09', 3, 'explicit_marker'),
  unique('hai set dấu nhân Unicode', 'set xanh ×2', 'g12', 2, 'explicit_marker'),
  unique('sáu set dấu nhân cách số', 'set xanh × 6', 'g12', 6, 'explicit_marker'),
  unique('hai quần số nguyên cuối câu', '49 xanh m 2', 'g01', 2, 'explicit_integer'),
  unique('mười váy số nguyên cuối câu', 'váy trắng 10', 'g05', 10, 'explicit_integer'),
  unique('SKU số thêm số lượng có ký hiệu', '1024 2c', 'g04', 2, 'explicit_marker'),
  unique('SKU số kèm cỡ rồi số lượng', '1024 29 2c', 'g04', 2, 'explicit_marker'),
  unique('cỡ số rồi số lượng trần', 'qt9 đen 29 2', 'g10', 2, 'explicit_integer'),
  unique('cỡ 30 rồi số lượng ba', 'quần tây 30 đen 3 cái', 'g11', 3, 'explicit_marker'),
  unique('màu nhiều từ cộng số lượng', 'áo7 đỏ đô xl 2c', 'g07', 2, 'explicit_marker'),
  unique('đảo màu cỡ vẫn giữ số lượng', 'áo7 xl đỏ đô x4', 'g07', 4, 'explicit_marker'),
  unique('freesize và số lượng', 'áo hồng freesize 2 chiếc', 'g09', 2, 'explicit_marker'),
  unique('bí danh dài rồi số lượng', 'quần xanh đậm 2c', 'g04', 2, 'explicit_marker'),
  unique('số 29 có ký hiệu là số lượng chứ không là cỡ', '1024 29c', 'g04', 29, 'explicit_marker'),
  unique('giới hạn dưới một sản phẩm', '49 xanh m 1c', 'g01', 1, 'explicit_marker'),
  unique('giới hạn trên 1000 sản phẩm', '49 xanh m 1000c', 'g01', 1000, 'explicit_marker'),
  unique('số lượng có số không ở đầu', 'váy be 002 cái', 'g06', 2, 'explicit_marker'),
  unique('bí danh số vẫn cho thêm số lượng', '1000 2c', 'g08', 2, 'explicit_marker'),
  unique('bí danh chứa 2c vẫn cho thêm số lượng', 'combo 2c x3', 'g12', 3, 'explicit_marker'),
];

const ambiguityCases = [
  ambiguous('mã mẫu chưa chọn biến thể', '49', ['g01', 'g02', 'g03']),
  ambiguous('bí danh dùng chung chưa có thuộc tính', 'Q49', ['g01', 'g02', 'g03']),
  ambiguous('màu xanh có hai cỡ', '49 xanh', ['g01', 'g03']),
  ambiguous('cỡ L có hai màu', '49 l', ['g02', 'g03']),
  ambiguous('bí danh quần xanh có hai cỡ', 'quần xanh', ['g01', 'g03']),
  ambiguous(
    'chung bí danh thêm số lượng vẫn chưa đủ chọn SKU',
    'q49 2c',
    ['g01', 'g02', 'g03'],
    2,
    'explicit_marker',
  ),
  ambiguous(
    'màu xanh thêm số lượng vẫn thiếu cỡ',
    '49 xanh x3',
    ['g01', 'g03'],
    3,
    'explicit_marker',
  ),
  ambiguous('mẫu váy chưa chọn màu', 'cv12', ['g05', 'g06']),
  ambiguous('mẫu váy cùng cỡ S', 'cv12 s', ['g05', 'g06']),
  ambiguous('mẫu áo chưa chọn màu cỡ', 'áo7', ['g07', 'g08']),
  ambiguous('quần tây đều màu đen', 'qt9 đen', ['g10', 'g11']),
  ambiguous(
    'quần tây màu đen có số lượng vẫn thiếu cỡ',
    'quần tây đen 2 chiếc',
    ['g10', 'g11'],
    2,
    'explicit_marker',
  ),
];

const rejectedConversationCases = [
  ['lời chào không phải chốt', 'chào shop nha'],
  ['hỏi giá không chọn biến thể', '49 bao nhiêu tiền vậy shop'],
  ['hỏi còn hàng', '49 xanh m còn không'],
  ['xin tư vấn cân nặng', 'em 55kg mặc cỡ nào shop'],
  ['không bỏ qua lời hủy ở cuối', '49 xanh m 2c hủy giúp em'],
  ['không coi câu hủy đầu câu là chốt', 'hủy 49 xanh m'],
  ['không tự bỏ lời phủ định', 'không lấy 49 xanh m'],
  ['lời đổi màu cần người đọc', '49 xanh m đổi đỏ nha'],
  ['lời nhờ chọn hàng cần người đọc', 'lấy giúp em 49 xanh m'],
  ['câu có xin vui lòng không tự rút gọn', '49 xanh m cho em 2 cái nhé'],
  ['hai SKU trong một bình luận không tự chốt một', '49 xanh m 2c và cv12 trắng s 1c'],
  ['hai biến thể có dấu cộng', '49 xanh m + đỏ l'],
  ['số điện thoại cuối bình luận không phải số lượng', '49 xanh m 0901234567'],
  ['địa chỉ giao hàng không phải thuộc tính', '49 xanh m giao Hà Nội'],
  ['emoji chưa đăng ký không tự bỏ', '49 xanh m ❤️'],
  ['ký hiệu hashtag không tự bỏ', '#49 xanh m'],
  ['không ghép mã và màu thiếu khoảng cách', '49xanh m'],
  ['không ghép cỡ với số lượng thiếu khoảng cách', '49 xanh m2c'],
  ['không tách dấu phẩy tự suy diễn', '49,xanh,m,2c'],
  ['không bỏ dấu câu cuối', '49 xanh m 2c!'],
  ['không sửa lỗi gõ tên màu', '49 xannh m'],
  ['không thay từ màu tiếng Anh', '49 blue m'],
  ['màu không tồn tại', '49 tím m'],
  ['cỡ không tồn tại', '49 xanh xxl'],
  ['không đoán xanh đậm thành xanh', '49 xanh đậm m'],
  ['bí danh dài sai thuộc tính không lùi về bí danh ngắn', 'quần xanh đậm l 2c'],
  ['bí danh set xanh dài hơn mã SET không tự bỏ phần thuộc tính còn lại', 'set xanh ngọc m'],
  ['không lặp thuộc tính', '49 xanh xanh m'],
  ['không bỏ từ size tự do', '49 xanh size m'],
  ['không mặc định freesize từ chữ F chưa đăng ký', 'áo hồng f'],
  ['không coi màu đỏ là đỏ đô', 'áo7 đỏ xl'],
  ['không bỏ dấu tiếng Việt trong bí danh', 'vay trang'],
  ['không bỏ dấu tiếng Việt trong màu', 'cv12 trang s'],
  ['không NFKC mã fullwidth thành mã thật', '４９ xanh m'],
  ['không xóa zero-width ghép mã', '4\u200b9 xanh m'],
  ['bí danh ngưng sử dụng không còn gợi ý', 'hết'],
  ['mã không tồn tại', 'CV999 trắng s'],
  ['nội dung giống câu lệnh vẫn chỉ là dữ liệu', '49 xanh m; DELETE FROM products'],
  ['nội dung HTML không được hiểu thành mã', '<b>49 xanh m</b>'],
].map(([label, text]) => rejected(label, text));

const invalidQuantityCases = [
  ['không sản phẩm', '0c'],
  ['số lượng âm', '-1c'],
  ['số lượng dương có dấu cộng', '+2c'],
  ['số lẻ dùng dấu chấm', '1.5c'],
  ['số lẻ dùng dấu phẩy', '1,5c'],
  ['quá giới hạn', '1001c'],
  ['ký hiệu khoa học', '1e3c'],
  ['số lớn vượt số nguyên an toàn', '9007199254740993c'],
  ['vô cực', 'Infinityc'],
  ['không phải số', 'NaNc'],
  ['số hex', '0x10c'],
  ['số Unicode toàn chiều', '２c'],
  ['dấu nhân với số không', 'x0'],
  ['dấu nhân với số âm', '×-2'],
  ['dấu nhân với số lẻ', 'x2.5'],
  ['dấu nhân vượt giới hạn', '×1001'],
  ['không sản phẩm viết số trần', '0'],
  ['số âm viết trần', '-2'],
  ['số trần có phân cách nghìn', '1.000'],
  ['số lượng bằng chữ chưa hỗ trợ', 'hai cái'],
].map(([label, suffix]) => rejected(label, `49 xanh m ${suffix}`, 'INVALID_QUANTITY'));

const unicodeCases = [
  unique('chữ hoa tiếng Việt', 'VÁY TRẮNG', 'g05'),
  unique('chữ hoa thường xen kẽ', 'Áo Đỏ Đô', 'g07'),
  unique('khoảng trắng đầu và cuối', '  váy be  ', 'g06'),
  unique('nhiều khoảng trắng giữa thuộc tính', '49   xanh   m', 'g01'),
  unique('tab giữa mã màu cỡ', '49\txanh\tm', 'g01'),
  unique('xuống dòng giữa thuộc tính', '49\nxanh\nm', 'g01'),
  unique('NBSP từ copy bình luận', '49\u00a0xanh\u00a0m', 'g01'),
  unique('em-space từ copy bình luận', '49\u2003xanh\u2003m', 'g01'),
  unique('narrow NBSP trước đơn vị', 'váy trắng 2\u202fcái', 'g05', 2, 'explicit_marker'),
  unique('BOM đầu nội dung', '\ufeffáo kem', 'g08'),
  unique('NEXT LINE Unicode giữa thuộc tính', '49\u0085xanh\u0085m', 'g01'),
  unique('dấu tổ hợp trong bí danh', 'VÁY TRẮNG', 'g05'),
  unique('dấu tổ hợp trong màu nhiều từ', 'áo7 đỏ đô xl', 'g07'),
  unique('dấu tổ hợp trong bí danh dài', 'quần xanh đậm 2c', 'g04', 2, 'explicit_marker'),
];

const withProduct = (id, changes) => ({
  ...catalog,
  products: catalog.products.map((row) => (row.id === id ? { ...row, ...changes } : row)),
});
const withVariant = (id, changes) => ({
  ...catalog,
  variants: catalog.variants.map((row) => (row.product_id === id ? { ...row, ...changes } : row)),
});
const catalogSafetyCases = [
  review('SKU tạm luôn cần xác nhận', 'TẠM', 'g13'),
  review('bí danh SKU tạm vẫn cần xác nhận', 'mẫu thử', 'g13'),
  review('SKU cũ không có biến thể', 'CŨ', 'g14'),
  review(
    'SKU có biến thể chưa xác nhận',
    'JEAN-XANH-M',
    'g01',
    withVariant('g01', { mapping_status: 'needs_review' }),
  ),
  review(
    'SKU xác nhận nhưng sản phẩm vẫn tạm',
    'JEAN-XANH-M',
    'g01',
    withProduct('g01', { provisional: true }),
  ),
  review(
    'thiếu cờ provisional không được coi đã duyệt',
    'JEAN-XANH-M',
    'g01',
    withProduct('g01', { provisional: undefined }),
  ),
  review('style không có trong dữ liệu đã tải', 'JEAN-XANH-M', 'g01', { ...catalog, styles: [] }),
  review(
    'style null không được coi đã duyệt',
    'JEAN-XANH-M',
    'g01',
    withVariant('g01', { style_id: null }),
  ),
  review('nhiều dòng biến thể không được tùy chọn một', 'JEAN-XANH-M', 'g01', {
    ...catalog,
    variants: [...catalog.variants, { ...catalog.variants[0], id: 'duplicate' }],
  }),
  {
    ...ambiguous('bí danh va chạm mã SKU cần chọn lại', 'JEAN-XANH-M', ['g01', 'g02']),
    override: {
      ...catalog,
      aliases: [...catalog.aliases, { alias_text: 'JEAN-XANH-M', product_id: 'g02', active: true }],
    },
  },
  {
    ...ambiguous('mã mẫu va chạm mã SKU vẫn báo tất cả ứng viên', '49', [
      'g01',
      'g02',
      'g03',
      'g08',
    ]),
    override: withProduct('g08', { code: '49' }),
  },
  {
    ...ambiguous('không bỏ ứng viên chưa duyệt để chọn ứng viên đã duyệt', 'quần xanh', [
      'g01',
      'g03',
    ]),
    override: withVariant('g03', { mapping_status: 'needs_review' }),
  },
  {
    ...unique('bí danh trùng cùng SKU chỉ có một ứng viên', 'váy trắng', 'g05'),
    override: {
      ...catalog,
      aliases: [...catalog.aliases, { alias_text: 'VÁY TRẮNG', product_id: 'g05', active: true }],
    },
  },
  {
    ...rejected('bí danh mồ côi không gán sang SKU khác', 'hàng mồ côi', 'UNKNOWN_CODE'),
    override: {
      ...catalog,
      aliases: [
        ...catalog.aliases,
        { alias_text: 'hàng mồ côi', product_id: 'not-loaded', active: true },
      ],
    },
  },
  {
    ...rejected('catalog chưa tải không được đoán SKU', '49 xanh m', 'UNKNOWN_CODE'),
    override: {},
  },
];

const groups = {
  exactCases,
  attributeCases,
  quantityCases,
  ambiguityCases,
  rejectedConversationCases,
  invalidQuantityCases,
  unicodeCases,
  catalogSafetyCases,
};

describe('Vietnamese livestream parser corpus (suggestions only)', () => {
  it('contains at least 100 independently named scenarios across business/safety categories', () => {
    const scenarios = Object.values(groups).flat();
    expect(scenarios.length).toBeGreaterThanOrEqual(100);
    expect(new Set(scenarios.map((row) => row.label)).size).toBe(scenarios.length);
    expect(Object.keys(groups)).toHaveLength(8);
  });
  for (const [group, cases] of Object.entries(groups))
    describe(group, () => {
      it.each(cases)('$label — $text', ({ text, expected, ids, override }) => {
        const source = freeze(override || catalog);
        const before = JSON.stringify(source);
        const result = parseLiveComment(text, source);
        expect(result).toMatchObject({ version: '1', ...expected });
        expect(result.normalized).toBe(normalizeLiveText(text));
        expect(new Set(result.candidates.map((row) => row.product_id)).size).toBe(
          result.candidates.length,
        );
        if (ids) expect(result.candidates.map((row) => row.product_id)).toEqual(ids);
        if (result.status !== 'unique') expect(result.product_id).toBeNull();
        if (result.status === 'unique')
          expect(result.candidates[0].mapping_status).toBe('confirmed');
        expect(JSON.stringify(source)).toBe(before);
        expect(result).not.toHaveProperty('reservation_id');
        expect(result).not.toHaveProperty('ticket_id');
      });
    });
});
